# Generated by Django 2.2.8 on 2020-01-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.CharField(default='Snrvuf9sffNsnnYYSNZGv8', editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('del_state', models.PositiveIntegerField(choices=[(0, '已删除'), (1, '默认')], db_index=True, default=1, verbose_name='删除状态')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('is_super', models.BooleanField(default=False, verbose_name='管理员')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='创建来源')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_time'],
            },
        ),
    ]
