# Generated by Django 2.2.8 on 2020-01-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200107_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=18, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='fjS2LjCNiQ3qBfzVSs2Ch2', editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
